### PR TITLE
Updates for html output

### LINKED ISSUE #73: HTML friendly output
<br/>
<br/>
<br/>

**Is your feature request related to a problem? Please describe.**
We use Jenkins to run popeye and want to present the result as HTML report.

**Describe the solution you'd like**
Either a direct html output or jurassic output should use html friendly characters (see screenshot).

**Describe alternatives you've considered**
We also use Junit format and let Jenkins read that, but the normal text output is way clearer for a developer.

**Additional context**
image

### PR DESCRIPTION
**Pull request by BarakStout**
Starter code for HTML output. Closes #73 

Run using: `go run main.go -o html` 

Output in browser: 
popeye-html-2020-02-10

### CODE REVIEW

**Comment by derailed** [comment]
@BarakStout You Sir Rock!! Very cool use of go templates to achieve this! I think the ui needs a bit of TLC but this is very awesome first pass indeed!
I'll take a closer look but almost fell off my chair when I saw this PR. Very very cool! Thank you!!

**Comment by BarakStout** [comment]
@derailed Thank you! 

I figured this can work as starter code for the UI.

**Comment by santinoncs** [comment]
I am using jenkins to show the output and this new feature would be very useful 
thanks for the work!

**Comment by derailed** [comment]
@BarakStout @santinoncs this feature is now available in v0.7.0! Thank you for your work Barak!

**Pull request closed without merging**
