### PR TITLE
Adds Popeye codes list

### LINKED ISSUE #110: List with Popeye Codes
Not really a feature, but referencing an older issue, where I asked for a list of codes that Popeye displays.

[Issue #95 ](https://github.com/derailed/popeye/issues/95)

I'm not sure where to put this list, so I didn't create a Pull request for this.

I parsed that codes file and created a Markdown table with it (excerpt):

# List of Popeye Codes

### Container

| Code | Message | Severity | Info / Reference |
| --- | --- | --- | --- |
| 100 | Untagged docker image in use | 3 |  |
| 101 | Image tagged "latest" in use | 2 |  |
| 102 | No probes defined | 2 |  |
| 103 | No liveness probe | 2 |  |
| 104 | No readiness probe | 2 |  |
| 105 | "%s probe uses a port#, prefer a named port" | 1 |  |
| 106 | No resources requests/limits defined | 2 |  |
| 107 | No resource limits defined | 2 |  |
| 108 | "Unnamed port %d" | 1 |  |
| 109 | CPU Current/Request (%s/%s) reached user %d%% threshold (%d%%) | 2 |  |
| 110 | Memory Current/Request (%s/%s) reached user %d%% threshold (%d%%) | 2 |  |
| 111 | CPU Current/Limit (%s/%s) reached user %d%% threshold (%d%%) | 3 |  |
| 112 | Memory Current/Limit (%s/%s) reached user %d%% threshold (%d%%) | 3 |  |

@derailed What do you think about this? Do you have any ideas to format it in a better way?

### PR DESCRIPTION
**Pull request by danibaeyens**
Fixes #110. It contains the full list of codes. There is no further info, yet.
Also, I've noticed code 502 is apparently missing in the code...

### CODE REVIEW

**Comment by marians** [comment]
I agree this should be available in docs!

Two nitpicks:

- The variable placeholders like `%d` make the descriptions hard to read. I would suggest to remove them here and opt for better readability.
- A blank line after each section headline would be appreciated.

**Comment by danibaeyens** [comment]
What do you think it's better?
Something explanatory like:
* Unhealthy `<pods>` desired but have `<pods>` available
* At current load, CPU under allocated. Current:`<cpu_usage>` vs Requested:`<cpu_requested>` (`<diff_percentage>`)

or just a new wording for each rule?

**Comment by marians** [comment]
I was thinking a new wording. E. g. 

- `%s probe uses a port#, prefer a named port` -> Probe uses a port number, prefer a named port
- `Unnamed port %d` -> Unnamed port
- `CPU Current/Request (%s/%s) reached user %d%% threshold (%d%%)` -> CPU Current/Request reached user threshold

**Comment by knowings** [comment]
Hi all. First thx for the effort on `popeye` in general and this documentation contribution especially.

I would like to see the last column (`Info / Reference`) filled with more data as most of the posts are cryptic for newbies and don't give any internet search direct results.

**Comment by derailed** [comment]
@danibaeyens Thank you for this PR Dany!

**Pull request merged**
