### PR TITLE
Add S3 support

### PR DESCRIPTION
**Pull request by guusvw**
This PR will add support to upload reports directly to AWS S3.

Current state, already working 🎉 

~There is still documentation & some refactoring missing.~

Use case:
Our current workflow is currently to run Popeye on a regular base via a CronJob (once a week) and afterwards post the report to AWS, this will be easier when it's possible to persist the report to S3.

### CODE REVIEW

**Comment by derailed** [comment]
@guusvw That is sooo cool!! Thank you so much Guus for your efforts and contributions!! 
I'll take a peek...

**Comment by guusvw** [comment]
@derailed I had a look at the "codebeat" issues, but I think currently it is quite hard to fix them, because they are caused mainly of the flag handling.
I could adjust the "codebeat" config if u want.

**Comment by derailed** [comment]
@guusvw  Thank you for looking into this. Yes I think we could loosen things a bit. Codebeat is kind of lame for go. I think we could set ivar to 15 info and loc to 300. And see if they pick them up which is not always the case ;(

**Comment by guusvw** [comment]
@derailed I adjusted the CodeBeat settings and rebased the PR

**Comment by derailed** [comment]
@guusvw Thank you for make these changes! What are your thoughts about getting ride of the flag `save-to-s3` and just dumping to S3 if the `s3bucket` is set also going to s3-bucket vs s3bucket? So 

```shell
# ie we are specifying the s3 bucket in the cli so saveToS3 is implicit...
popeye -o json --s3-bucket=xxx 
#vs
popeye  -o json --save-to-s3  --s3-bucket
```

**Comment by guusvw** [comment]
@derailed sounds like a good idea. Totally not biased with the name of the flag and having one flag less is something I like ;) 
I think I will and can add those changes still today.

**Comment by derailed** [comment]
@guusvw Very cool. Thank you so much for your consideration! Yes I think simpler interface is always good. Thank you Guus!!

**Comment by guusvw** [comment]
@derailed removed the `save-to-s3` flag and renamed `s3bucket` to `s3-bucket`.
Have still to update the README now ;) will do tomorrow morning, missing some sleep (thanks to the Super Bowl ^^)

**Comment by derailed** [comment]
@guusvw Thank you for making these updates while still under superbowl withdrawals ;( It was indeed an excellent game!

**Comment by guusvw** [comment]
@derailed the `README.md` is now also aligned with the implementation ;)

**Comment by derailed** [comment]
@guusvw Very cool! Thank you Guus for seeing this all the way thru!

**Pull request merged**
