### PR TITLE
add dumpDir function

### PR DESCRIPTION
**Pull request by guusvw**
which looks up ENV "POPEYE_DUMP_DIR"
  or fallback to default behaviour

### CODE REVIEW

**Comment by derailed** [comment]
@guusvw Thank you for this PR! Looks good. Just a few pics...

1. Dump is used internally (probably not a great name for it) perhaps surface the option as POPEYE_REPORT_DIR or POPEYE_SANITIZER_DIR or something like that.
2. dd is typically idiomatic in GO for a collection var so perhaps `d` better fit that bill?
3. Would need to also add docs in the README.md for how to override the sanitizers dir location

Thank you!!

**Comment by guusvw** [comment]
@derailed Thanks for the feedback ;) will do.

**Comment by guusvw** [comment]
@derailed could you review again?

**Comment by derailed** [comment]
@guusvw Looks good. Thank you for making these changes!

**Pull request merged**
