### PR TITLE
Allow container exclusions based on regex

### PR DESCRIPTION
**Pull request by bencouture**

### CODE REVIEW

**Comment by derailed** [comment]
@bencouture - Looks like test suite is failing.

**Comment by bencouture** [comment]
It looks like the test were passing on commit b5be4fd, then started failing when you merged 6aee061. Could you try just re-running the tests? All the tests still pass if I check out my master branch and run `make test`, and I can't think of any reason why changing the readme should ever cause the tests to suddenly start failing, so maybe it was a fluke?

**Review by derailed — APPROVED** [review]
@bencouture Thanks for the updates Ben!

**Comment by derailed** [comment]
@bencouture Looks like there are some conflicts still. Could you resolve those? Thank you!

**Comment by derailed** [comment]
no activity - closing

**Pull request closed without merging**
